title:  <p align="center"> Kandasami Pirahalathan </p>
logo: /assets/img/MyPhoto.jpeg
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/kandasami/">LinkedIn</a> |
  <a href="https://github.com/kandasami/">GitHub</a>
  <br>   
  I'm working as a Development Architect in SAP Labs India. 
  I am having 15 years of experience in SAP ERP Technologies and SAP Middleware Technologies.
  <br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
